# Generated by Django 4.2.30 on 2026-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.CharField(blank=True, default='Full', max_length=20),
        ),
    ]
