# Generated by Django 3.2.25 on 2026-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20260521_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt', models.CharField(default='Gallery Image', max_length=255)),
                ('span', models.CharField(choices=[('col-span-1 row-span-1', 'Standard (1x1)'), ('col-span-2 row-span-2', 'Large Square (2x2)'), ('col-span-1 row-span-2', 'Vertical Rectangle (1x2)'), ('col-span-2 row-span-1', 'Horizontal Rectangle (2x1)')], default='col-span-1 row-span-1', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero_bg', 'Hero Background'), ('about_story', 'About Story Image'), ('chef_photo', 'Chef Photo'), ('chef_signature', 'Chef Signature'), ('reservation_bg', 'Reservation Background')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='site_assets/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
