# Generated by Django 4.2.30 on 2026-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_galleryimage_siteasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.CharField(blank=True, default='1 Portion', help_text='e.g. 1 Portion, 500g, 2 Pcs', max_length=50),
        ),
    ]
