# Generated by Django 4.2.30 on 2026-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_half_option',
            field=models.BooleanField(default=True, help_text='Whether Half portion option is available'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for Half portion', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for Full portion', max_digits=10),
        ),
    ]
