# Generated by Django 4.2.30 on 2026-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_has_half_option_menuitem_price_half_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='serves',
            field=models.CharField(blank=True, default='Serves 1', help_text='e.g. Serves 1, Serves 2, Serves 1-2', max_length=50),
        ),
    ]
