# Generated by Django 4.2.30 on 2026-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='serves_half',
            field=models.CharField(blank=True, default='Serves 1-2', help_text='Serving size for Half portion, e.g. Serves 1-2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='serves',
            field=models.CharField(blank=True, default='Serves 1', help_text='Serving size for Full portion, e.g. Serves 3-4, Serves 1', max_length=50),
        ),
    ]
