# Generated by Django 4.2.30 on 2026-07-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_serves_half_alter_menuitem_serves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
    ]
