# Generated by Django 6.0.7 on 2026-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_menuitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteasset',
            name='key',
            field=models.CharField(choices=[('hero_bg', 'Hero Background'), ('logo', 'Site Logo'), ('about_story', 'About Story Image'), ('chef_photo', 'Chef Photo'), ('chef_signature', 'Chef Signature'), ('reservation_bg', 'Reservation Background')], max_length=50, unique=True),
        ),
    ]
